// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI860rY_P-yytu9n2aThb_KVbwcyp8Jb4',
    appId: '1:7285013352:web:0d19449a910a9ff77934dd',
    messagingSenderId: '7285013352',
    projectId: 'gotoscoai-ec5bd',
    authDomain: 'gotoscoai-ec5bd.firebaseapp.com',
    storageBucket: 'gotoscoai-ec5bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgBU-BSrX6YQejqD-4AuBnUNvWYNH9Rw0',
    appId: '1:7285013352:android:ccb2ff613e44ddee7934dd',
    messagingSenderId: '7285013352',
    projectId: 'gotoscoai-ec5bd',
    storageBucket: 'gotoscoai-ec5bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjJnunvm3Rv0e2Z2XxxtY1IbyMi1z5340',
    appId: '1:7285013352:ios:9fddbc171879a4d57934dd',
    messagingSenderId: '7285013352',
    projectId: 'gotoscoai-ec5bd',
    storageBucket: 'gotoscoai-ec5bd.firebasestorage.app',
    iosBundleId: 'com.example.gotoscoV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjJnunvm3Rv0e2Z2XxxtY1IbyMi1z5340',
    appId: '1:7285013352:ios:9fddbc171879a4d57934dd',
    messagingSenderId: '7285013352',
    projectId: 'gotoscoai-ec5bd',
    storageBucket: 'gotoscoai-ec5bd.firebasestorage.app',
    iosBundleId: 'com.example.gotoscoV3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI860rY_P-yytu9n2aThb_KVbwcyp8Jb4',
    appId: '1:7285013352:web:5801874ea0d477df7934dd',
    messagingSenderId: '7285013352',
    projectId: 'gotoscoai-ec5bd',
    authDomain: 'gotoscoai-ec5bd.firebaseapp.com',
    storageBucket: 'gotoscoai-ec5bd.firebasestorage.app',
  );

}